[target.thumbv6m-none-eabi]
runner = "elf2uf2-rs -d -s"

[unstable]
build-std = [
    "core",
    "compiler_builtins"
]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "trace"
